# gsd/report.py
from __future__ import annotations
import html
from pathlib import Path
from typing import Dict, Any

STYLE = """
body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Helvetica,Arial,sans-serif;margin:24px;}
h1{margin:0 0 8px 0;}
.cards{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0 20px;}
.card{border:1px solid #e5e7eb;border-radius:12px;padding:12px 14px;min-width:160px;box-shadow:0 1px 2px rgba(0,0,0,.03);}
.card .k{font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:.04em;}
.card .v{font-size:20px;font-weight:600;margin-top:4px;}
table{border-collapse:collapse;width:100%;margin-top:8px;}
th,td{border:1px solid #e5e7eb;padding:8px 10px;text-align:left;vertical-align:top;}
th{background:#f9fafb;font-weight:600;}
code{background:#f3f4f6;border:1px solid #e5e7eb;padding:2px 4px;border-radius:6px;}
.small{color:#6b7280;font-size:12px;}
footer{margin-top:28px;color:#6b7280;font-size:12px;}
"""

def render_html(run: Dict[str, Any]) -> str:
    c = run["counts"]
    dup_pct = (100.0 * c["dup_members"] / max(1, c["items"]))
    status = "Healthy ✅" if (c["dup_members"] == 0 and c["leakage"] == 0) else "Needs attention ⚠️"

    head = (
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<title>Golden-Set Doctor Report</title>"
        f"<style>{STYLE}</style></head><body>"
    )
    body = [
        f"<h1>Golden-Set Doctor Report</h1>"
        f"<div class='small'>Dataset: <code>{html.escape(run['dataset'])}</code></div>"
    ]

    body.append("<div class='cards'>")
    body.append(card("Status", status))
    body.append(card("Items", str(c["items"])))
    body.append(card("Dup clusters", str(c["dup_clusters"])))
    body.append(card("Dup members", f"{c['dup_members']} ({dup_pct:.1f}%)"))
    body.append(card("Leakage", str(c["leakage"])))
    body.append("</div>")

    # Duplicates
    if run["dup_clusters"]:
        rows = ["<table><thead><tr><th>Canonical ID</th><th>Canonical input</th><th>Members</th></tr></thead><tbody>"]
        for cl in run["dup_clusters"]:
            members = "<br>".join(
                f"<code>{html.escape(mid)}</code>: {html.escape(inp)}"
                for mid, inp in zip(cl["members"], cl["member_inputs"])
            )
            rows.append(
                f"<tr><td><code>{html.escape(cl['canonical'])}</code></td>"
                f"<td>{html.escape(cl['canonical_input'])}</td>"
                f"<td>{members or '-'}</td></tr>"
            )
        rows.append("</tbody></table>")
        body += ["<h2>Near-duplicate clusters</h2>"] + rows

    # Leakage
    if run["leakage"]:
        rows = ["<table><thead><tr><th>Item ID</th><th>File</th><th>Match score</th><th>Reason</th><th>Snippet</th></tr></thead><tbody>"]
        for hit in run["leakage"]:
            score = hit.get("score", 0.0)
            reason = hit.get("reason", "")
            rows.append(
                f"<tr><td><code>{html.escape(hit['item_id'])}</code></td>"
                f"<td><code>{html.escape(hit['file'])}</code></td>"
                f"<td>{float(score):.3f}</td>"
                f"<td>{html.escape(reason)}</td>"
                f"<td>{html.escape(hit['snippet'])}</td></tr>"
            )
        rows.append("</tbody></table>")
        body += ["<h2>Leakage matches</h2>"] + rows

    body.append("<footer>Generated by Golden-Set Doctor · LLM-only v1</footer>")
    return head + "\n".join(body) + "</body></html>"

def card(k: str, v: str) -> str:
    return f"<div class='card'><div class='k'>{k}</div><div class='v'>{v}</div></div>"

def save_html(run: Dict[str, Any], out_html: str) -> None:
    Path(out_html).write_text(render_html(run), encoding="utf-8")
